#!/usr/bin/env bash
# Pings an IP address 5 times, shows usage if no IP provided

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP 5 times
ping -c 5 "$1"
