#!/usr/bin/env bash
# This script configures localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Re-run with sudo if not root
if [ "$(id -u)" -ne 0 ]; then
    exec sudo "$0" "$@"
fi

# Overwrite /etc/hosts with ONLY required entries
tee /etc/hosts > /dev/null <<EOF
127.0.0.2 localhost
8.8.8.8 facebook.com
EOF
