#!/usr/bin/env bash
# This script configures localhost and facebook.com IP resolution

if [ "$(id -u)" -ne 0 ]; then
    sudo "$0" "$@"
    exit
fi

tmp_file=$(mktemp)

# Put correct entries FIRST
echo "127.0.0.2 localhost" > "$tmp_file"
echo "8.8.8.8 facebook.com" >> "$tmp_file"

# Add the rest of hosts file WITHOUT old entries
grep -v -E "127.0.0.1 localhost|127.0.0.2 localhost|facebook.com" /etc/hosts >> "$tmp_file"

cat "$tmp_file" > /etc/hosts
rm "$tmp_file"
